runtime: nodejs
env: flex

service: default

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5

env_variables:
  MY_VAR: my_value
  NODE_ENV: production

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
